apiVersion: apps/v1
kind: Deployment
metadata:
  name: aps-lstm-crf
  labels:
    name: aps-lstm-crf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aps-lstm-crf
  template:
    metadata:
      labels:
        app: aps-lstm-crf
    spec:
      containers:
      - name: aps-lstm-crf
        image: registry.wtg.ws/aps-lstm-crf-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "64Gi"
            cpu: "4"
        env:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-access-key
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-access-key
              key: S3_SECRET_ACCESS_KEY
  progressDeadlineSeconds: 2147483647
